var famous = {
    "core": {
        "Context": function () {},
        "ElementAllocator": function () {},
        "ElementOutput": function () {},
        "Engine": {
            "step": function () {},
            "pipe": function () {},
            "unpipe": function () {},
            "on": function () {},
            "emit": function () {},
            "removeListener": function () {},
            "getFPS": function () {},
            "setFPSCap": function () {},
            "getOptions": function () {},
            "setOptions": function () {},
            "createContext": function () {},
            "registerContext": function () {},
            "getContexts": function () {},
            "deregisterContext": function () {},
            "nextTick": function () {},
            "defer": function () {}
        },
        "Entity": {
            "register": function () {},
            "unregister": function () {},
            "get": function () {},
            "set": function () {}
        },
        "EventEmitter": function () {},
        "EventHandler": function () {},
        "Group": function () {},
        "Modifier": {
	    "opacityFrom" : function () {}
	},
        "OptionsManager": function () {},
        "RenderNode": {
	    "add" : function () {}
	},
        "Scene": function () {},
        "SpecParser": function () {},
        "Surface": {
	    "on" : function () {},
	    "setClasses" : function () {},
	    "setContent" : function () {}
	},
        "Transform": {
            "precision": {},
            "identity": {
                "0": {},
                "1": {},
                "2": {},
                "3": {},
                "4": {},
                "5": {},
                "6": {},
                "7": {},
                "8": {},
                "9": {},
                "10": {},
                "11": {},
                "12": {},
                "13": {},
                "14": {},
                "15": {}
            },
            "multiply4x4": function () {},
            "multiply": function () {},
            "thenMove": function () {},
            "moveThen": function () {},
            "translate": function () {},
            "thenScale": function () {},
            "scale": function () {},
            "rotateX": function () {},
            "rotateY": function () {},
            "rotateZ": function () {},
            "rotate": function () {},
            "rotateAxis": function () {},
            "aboutOrigin": function () {},
            "skew": function () {},
            "skewX": function () {},
            "skewY": function () {},
            "perspective": function () {},
            "getTranslate": function () {},
            "inverse": function () {},
            "transpose": function () {},
            "interpret": function () {},
            "average": function () {},
            "build": function () {},
            "equals": function () {},
            "notEquals": function () {},
            "normalizeRotation": function () {},
            "inFront": {
                "0": {},
                "1": {},
                "2": {},
                "3": {},
                "4": {},
                "5": {},
                "6": {},
                "7": {},
                "8": {},
                "9": {},
                "10": {},
                "11": {},
                "12": {},
                "13": {},
                "14": {},
                "15": {}
            },
            "behind": {
                "0": {},
                "1": {},
                "2": {},
                "3": {},
                "4": {},
                "5": {},
                "6": {},
                "7": {},
                "8": {},
                "9": {},
                "10": {},
                "11": {},
                "12": {},
                "13": {},
                "14": {},
                "15": {}
            }
        },
        "View": function () {},
        "ViewSequence": function () {}
    },
    "events": {
        "EventArbiter": function () {},
        "EventFilter": function () {},
        "EventMapper": function () {}
    },
    "inputs": {
        "Accumulator": function () {},
        "DesktopEmulationMode": function () {},
        "FastClick": function () {},
        "GenericSync": function () {},
        "MouseSync": function () {},
        "PinchSync": function () {},
        "RotateSync": function () {},
        "ScaleSync": function () {},
        "ScrollSync": function () {},
        "TouchSync": function () {},
        "TouchTracker": function () {},
        "TwoFingerSync": function () {}
    },
    "math": {
        "Matrix": function () {},
        "Quaternion": function () {},
        "Random": {
            "integer": function () {},
            "range": function () {},
            "sign": function () {},
            "bool": function () {}
        },
        "Utilities": {
            "clamp": function () {},
            "length": function () {}
        },
        "Vector": function () {}
    },
    "modifiers": {
        "Draggable": function () {},
        "Fader": function () {},
        "ModifierChain": function () {},
        "StateModifier": {
	    "setOpacity" : function () {} 
	}
    },
    "physics": {
        "PhysicsEngine": function () {},
        "bodies": {
            "Body": function () {},
            "Circle": function () {},
            "Particle": function () {},
            "Rectangle": function () {}
        },
        "constraints": {
            "Collision": function () {},
            "Constraint": function () {},
            "Curve": function () {},
            "Distance": function () {},
            "Snap": function () {},
            "Surface": function () {},
            "Wall": function () {},
            "Walls": function () {}
        },
        "forces": {
            "Drag": function () {},
            "Force": function () {},
            "Repulsion": function () {},
            "RotationalDrag": function () {},
            "RotationalSpring": function () {},
            "Spring": function () {},
            "VectorField": function () {}
        },
        "integrators": {
            "SymplecticEuler": {
                "integrateVelocity": function () {},
                "integratePosition": function () {},
                "integrateAngularMomentum": function () {},
                "integrateOrientation": function () {}
            }
        }
    },
    "surfaces": {
        "CanvasSurface": function () {},
        "ContainerSurface": function () {},
        "FormContainerSurface": function () {},
        "ImageSurface": function () {},
        "InputSurface": function () {},
        "SubmitInputSurface": function () {},
        "TextareaSurface": function () {},
        "VideoSurface": function () {}
    },
    "transitions": {
        "CachedMap": function () {},
        "Easing": {
            "inQuad": function () {},
            "outQuad": function () {},
            "inOutQuad": function () {},
            "inCubic": function () {},
            "outCubic": function () {},
            "inOutCubic": function () {},
            "inQuart": function () {},
            "outQuart": function () {},
            "inOutQuart": function () {},
            "inQuint": function () {},
            "outQuint": function () {},
            "inOutQuint": function () {},
            "inSine": function () {},
            "outSine": function () {},
            "inOutSine": function () {},
            "inExpo": function () {},
            "outExpo": function () {},
            "inOutExpo": function () {},
            "inCirc": function () {},
            "outCirc": function () {},
            "inOutCirc": function () {},
            "inElastic": function () {},
            "outElastic": function () {},
            "inOutElastic": function () {},
            "inBack": function () {},
            "outBack": function () {},
            "inOutBack": function () {},
            "inBounce": function () {},
            "outBounce": function () {},
            "inOutBounce": function () {}
        },
        "MultipleTransition": function () {},
        "SnapTransition": function () {},
        "SpringTransition": function () {},
        "Transitionable": {
	    "set" : function () {},
	    "get" : function () {},
	    "isActive" : function () {}
	},
        "TransitionableTransform": function () {},
        "TweenTransition": function () {},
        "WallTransition": function () {}
    },
    "utilities": {
        "KeyCodes": {
            "0": {},
            "1": {},
            "2": {},
            "3": {},
            "4": {},
            "5": {},
            "6": {},
            "7": {},
            "8": {},
            "9": {},
            "a": {},
            "b": {},
            "c": {},
            "d": {},
            "e": {},
            "f": {},
            "g": {},
            "h": {},
            "i": {},
            "j": {},
            "k": {},
            "l": {},
            "m": {},
            "n": {},
            "o": {},
            "p": {},
            "q": {},
            "r": {},
            "s": {},
            "t": {},
            "u": {},
            "v": {},
            "w": {},
            "x": {},
            "y": {},
            "z": {},
            "A": {},
            "B": {},
            "C": {},
            "D": {},
            "E": {},
            "F": {},
            "G": {},
            "H": {},
            "I": {},
            "J": {},
            "K": {},
            "L": {},
            "M": {},
            "N": {},
            "O": {},
            "P": {},
            "Q": {},
            "R": {},
            "S": {},
            "T": {},
            "U": {},
            "V": {},
            "W": {},
            "X": {},
            "Y": {},
            "Z": {},
            "ENTER": {},
            "LEFT_ARROW": {},
            "RIGHT_ARROW": {},
            "UP_ARROW": {},
            "DOWN_ARROW": {},
            "SPACE": {},
            "SHIFT": {},
            "TAB": {}
        },
        "Timer": {
            "setTimeout": function () {},
            "setInterval": function () {},
            "debounce": function () {},
            "after": function () {},
            "every": function () {},
            "clear": function () {}
        },
        "Utility": {
            "Direction": {
                "X": {},
                "Y": {},
                "Z": {}
            },
            "after": function () {},
            "loadURL": function () {},
            "createDocumentFragmentFromHTML": function () {},
            "clone": function () {}
        }
    },
    "views": {
        "ContextualView": function () {},
        "Deck": function () {},
        "DrawerLayout": function () {},
        "EdgeSwapper": function () {},
        "FlexibleLayout": function () {},
        "Flipper": function () {},
        "GridLayout": {
	    "sequenceFrom" : function () {}
	},
        "HeaderFooterLayout": {
	    "header" : {},
	    "footer": {},
	    "content" : {}
	},
        "Lightbox": function () {},
        "RenderController": function () {},
        "ScrollContainer": function () {},
        "Scroller": function () {},
        "Scrollview": function () {},
        "SequentialLayout": {
	    "sequenceFrom" : function () {}
	},
        "SizeAwareView": function () {}
    },
    "widgets": {
        "NavigationBar": function () {},
        "Slider": function () {},
        "TabBar": function () {},
        "ToggleButton": function () {}
    }
}
